<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error Account</title>
</head>
<body>
<h2>У вас нет прав на это действие</h2><br>

<form method="get" action="/">
    <input type="submit" value="Home page">
</form>
</body>
</html>