<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error404</title>
</head>
<body>
    <h2>Ничего не найдено по вашему запросу</h2><br>

    <form method="get" action="/">
        <input type="submit" value="Home page">
    </form>
</body>
</html>